### ISSUE TITLE
@{lipsum:quantity:type} generates one sequence only

### ISSUE THREAD

**Issue by tpinne** [holidaypirates/nucleus#10]
The substitution `@{lipsum:3:words}` only generates one word. It seems that the quantity parameter has no effect. Same for `sentences` and `paragraphs`.

node v5.1.0
npm v3.3.12
nucleus 1.0.4

**Comment by michaelseibt** [comment]
Thanks for pointing this out. It should be fixed in 1.0.5, so please update to the latest version.
