### ISSUE TITLE
doesnt understand scss mixin definition syntax without parens

### ISSUE THREAD

**Issue by derhedwig** [holidaypirates/nucleus#12]
nucleus-styleguide: 1.0.4
node: 4.5.0
npm: 2.15.9

The following code results in a TypeError during compilation:
```
/**
 * hides with display none important
 * @mixin hide
 */
@mixin hide {
  display: none !important;
}
```

The error:
```
node_modules/nucleus-styleguide/src/entities/Mixin.js:53
  var paramString = this.raw.descriptor.match(/\((.*)\)/)[1];

TypeError: Cannot read property '1' of null
```

It works with 
```
@mixin hide() {
```

Accoring to http://sass-lang.com/documentation/file.SASS_REFERENCE.html#mixins it is possible to define mixins without the parens...

**Comment by michaelseibt** [comment]
Hi @derhedwig, this was reported in #9 and has been resolved in 1.0.6 yesterday. Please update to the newest version and let me know if it works fine for you then.
