### ISSUE TITLE
How to add vendor css files

### ISSUE THREAD

**Issue by JeffAspen** [holidaypirates/nucleus#16]
How can I add vendor css files that I don't have in my scss files? It looks like the config.nucleus.json file only excepts one css file for preview. I need to call in boostrap.

**Comment by jcfariadias** [comment]
You can use gulp and gulp-concat to merge both vendor and css styles.

```Javacript
gulp.task('build-css',function(){
    return gulp.src(["./pathTo/css/vendor.css","/pathTo/css/styles.css])
                     .pipe(concat('unified.css'))
                     .pipe(gulp.dest('./pathTo/destinationCSS/));
```

**Comment by JeffAspen** [comment]
That worked, thanks.

**Comment by michaelseibt** [comment]
Hi @JeffAspen, thanks for that improvement idea!

This will be supported from version 1.0.7 - you may then specify an array of paths as 'css' property in the config.nucleus.json, which will all be included in the style guide.
