### ISSUE TITLE
Nucleus init terminated when terminal resized

### ISSUE THREAD

**Issue by ariona** [holidaypirates/nucleus#20]
[1]    3380 segmentation fault  nucleus init

**Comment by michaelseibt** [comment]
Hi @ariona , 

confirming this. It seems like this is a problem with the prompt package prompt-sync. I could both reproduce it with Nucleus and their example file.

I will get in contact with them and come back with any new info here.

**Comment by michaelseibt** [comment]
Are you by chance using iTerm or zsh? The error is not happening on sh-shell on MacOS. It would be really helpful if you could provide more information about your system / environment.

**Comment by ariona** [comment]
I am using zsh.

**Comment by michaelseibt** [comment]
Continuing in [prompt-sync](https://github.com/0x00A/prompt-sync/issues/24)
