### ISSUE TITLE
LESS support

### ISSUE THREAD

**Issue by allankikkas** [holidaypirates/nucleus#24]
Is there a reason that LESS support is not included by default?

Should be possible by adding a configuration option for preprocessor type change (css/scss/lesss) and from there switch syntax library from postcss-scss to postcss-less. Or am I missing something?

**Comment by michaelseibt** [comment]
Hi @allankikkas, thanks for your request. This will be available in version 1.1.0 - it will be possible to pass both SCSS files and  LESS files to Nucleus at the same time. I'll let you know once we released it.
