### ISSUE TITLE
Problem running Nucleus on documented example

### ISSUE THREAD

**Issue by paallaire** [holidaypirates/nucleus#3]
When I type "config config.nucleus.json nucleus", I receive a message and I'm not understand my mistake

 Found 1 files.
 Crawling main.css

 Take care! No type for DocBlock in main.css on line 12
 You need to specify at least the type of the element. Possible types are
 @nuclide (with @color and @mixin as special types), @atom (with @icon as
 special type), @molecule and @structure.

Skipping unknown entity type.

Do you have an idea ?

main.css
`/**
 * @atom Button
 * @section Navigation
 * @description
 *  Buttons for various purposes.
 * @markup
 *   <button class="button">A button</button>
 *   <button class="button button--alert">
 *     An alert button
 *   </button>
 */
.button {
 /* ... */
 &.button--alert { /* ... */ }
}

/**
 * This is the prefered way to set the description.
 * Since this DocBlock is missing the @section
 * annotation, it would be shown in the generic
 * section "Other". Please note the empty line
 * after this block of text.
 *
 * @nuclide Language
 */
$config--lang: "en"`

**Comment by michaelseibt** [comment]
Hi paallaire! Your example is working fine for me. Could you please provide the following information?

* Node version
* NPM version

Here are the steps that I've tried:

* Create a new file main.css
* Paste the above example in main.css
* In terminal, run `nucleus main.css`

The output is:

```
 Found 1 files.
 🕐  Crawling test.css
 Finished! Took me 0 seconds.
```

I'm not sure how you got to run `config config.nucleus.json nucleus`. Are you used to right-to-left typing?

**I think the appropriate command for you might be `nucleus --config config.nucleus.json`.**

**Comment by paallaire** [comment]
I managed to make it work :

I have to save the file in ( UNIX LF ).

**Comment by michaelseibt** [comment]
Confirmed in #4 and will be fixed in next version.
