### ISSUE TITLE
Config key "script" misstake?

### ISSUE THREAD

**Issue by harapeko** [holidaypirates/nucleus#47]
I think `scripts` is correct
`script` is misstake

https://holidaypirates.github.io/nucleus/configuration.html
>Javascript files includes
Config key
script

[nucleus/assets/views/common/layout.pug](https://github.com/holidaypirates/nucleus/blob/01b56a9fa07d006350adfe0c8fc67a06e7200292/assets/views/common/layout.pug#L41)

**Comment by pieplu** [comment]
True! I made a mistake on the doc

**Comment by harapeko** [comment]
thx : )
i confirmed it !
