### ISSUE TITLE
Support for !default color variables

### ISSUE THREAD

**Issue by Bartozzz** [holidaypirates/nucleus#50]
```scss
/**
 * ...
 *
 * @color
 * @section Default colors
 */
$color-text: #000 !default;
```

When building, it outputs: `Error: Unable to parse color from string "#000 !default"`.

I think `nucleus` should remove the `!default` keyword automatically when parsing *SCSS variables*. If there's a reason why this feature is not implemented, there should be at least a possibility to specify color directly in the documentation, like so: `@color #000` (it could be a workaround for some others issues, ex. #9).

---

Nucleus version: 1.1.0
Node version: 7.8.0
NPM version: 4.2.0

**Comment by michaelseibt** [comment]
Thanks a lot! Version bumped just now.
