### ISSUE TITLE
[suggestion] Consider removing sweetalert

### ISSUE THREAD

**Issue by tipsy** [holidaypirates/nucleus#60]
Nucleus is a really nice library. It generates clean and beautiful styleguides, but the alert popping up informing user that they have copied a snippet is pretty distracting. A simple tooltip above the button would be a better solution, imo: 

![copied](https://user-images.githubusercontent.com/1521451/27598608-5161dc48-5b66-11e7-8eea-29cff9c75a9b.png)

**Comment by pkkummermo** [comment]
I think #70 might've fixed some of the issues with Sweetalert.
