### ISSUE TITLE
When installing with yarn, template file disappears

### ISSUE THREAD

**Issue by harapeko** [holidaypirates/nucleus#71]
OS: Ubuntu 14.04.5 LTS
Node JS: v8.7.0

# error

```
yarn run v1.2.1
$ nucleus --config ./config.nucleus_pc.json

 Whoops! Template folder is not valid.

 Double-check the template property in the configuration. This should
 be a valid folder with template files to generate a valid styleguide.Default
 template is used. Btw, the current working dir is /home/ubuntu/workspace


 Found 117 files.
 🕐  Crawling resources/assets/shared/sass/_generic.box-sizing.scssfs.js:653
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/home/ubuntu/workspace/node_modules/nucleus-styleguide/src/../assets/views/atoms.pug'
    at Object.fs.openSync (fs.js:653:18)
    at Object.fs.readFileSync (fs.js:554:33)
    at handleTemplateCache (/home/ubuntu/workspace/node_modules/pug/lib/index.js:215:37)
    at Object.exports.renderFile (/home/ubuntu/workspace/node_modules/pug/lib/index.js:428:10)
    at Object.<anonymous> (/home/ubuntu/workspace/node_modules/nucleus-styleguide/index.js:97:19)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
```

# npm install

![npm-install](https://user-images.githubusercontent.com/1858578/34202915-9540e3e2-e5bc-11e7-976f-bc9acd179170.png)

# yarn install

![yarn-install](https://user-images.githubusercontent.com/1858578/34202925-9ccb5bd8-e5bc-11e7-851e-299a6b60d499.png)

**Comment by harapeko** [comment]
I prepared a custom theme instead
It works without problems!

thanks : )

>Template
If you want customize the generated layout you can copy the [default theme]
(https://github.com/holidaypirates/nucleus/tree/master/assets/views) and customize it.

![2017-12-20 19 44 32](https://user-images.githubusercontent.com/1858578/34203384-42967ea2-e5be-11e7-802d-b0279827ea7a.png)

**Comment by lcherpit** [comment]
It's a bit old. The answer was probably in the yarn autoclean documentation. Have you got a  .yarnclean file in your root directory? https://classic.yarnpkg.com/en/docs/cli/autoclean/

**Comment by harapeko** [comment]
I'll close this now that the time has moved on and it's been resolved.
thanks👍
