### ISSUE TITLE
Ading content json asociated to atoms

### ISSUE THREAD

**Issue by cromozooom** [holidaypirates/nucleus#8]
Is possible to have a special section (like @JSONcontent) where I can spcify the content for every molecule?

**Comment by michaelseibt** [comment]
Hi cromozooom!

Could you give some more details, please? What are you referring to? The markup?
Maybe provide an example DocBlock how you imagine this.

**Comment by cromozooom** [comment]
I wish to have the standard content inside a JSON file for every component, if this is possible
![image](https://cloud.githubusercontent.com/assets/2906936/17923502/5a0ae6f4-69dc-11e6-9720-e474852517e9.png)

**Comment by cromozooom** [comment]
One of you just implemented @script annotation. This is practically same, but for CONTENT. (https://github.com/holidaypirates/nucleus/pull/15/files#diff-0)
